### PR TITLE
Rename to solution.cpp.

### LINKED ISSUE #1: There is no file with the name `CPP/solution.cpp`

### PR DESCRIPTION
**Pull request by JigaoLuo**
Signed-off-by: Jigao Luo <luojigao@outlook.com>

Fix #1

### CODE REVIEW

**Comment by rth** [comment]
Thanks for catching this!  No actually it should be called main.cpp, the README needs updating. Would you mind doing that?

**Comment by JigaoLuo** [comment]
But I see the python has the `solution.py`. 
Let me fix the README.

**Comment by rth** [comment]
Yes, it's just that the competition platform for arbitrary reasons cannot currently have the same filename with different extensions. So the workaround right now was to rename solution.cpp to main.cpp

**Comment by rth** [comment]
Thanks!

**Pull request merged**
